### ISSUE TITLE
Similar project qdomyos-zwift

### ISSUE THREAD

**Issue by cagnulein** [ptx2/gymnasticon#23]
I found you searching on github, i started a similar project some weeks ago 😄 

https://github.com/cagnulein/qdomyos-zwift
![ui-mac](https://user-images.githubusercontent.com/48216/96681697-ff49e180-1377-11eb-95ea-c03531d5534b.png)

**Comment by ptx2** [comment]
Nice one!

**Comment by igeo** [comment]
I have a FlyWheel studio bike instead of FlyWheel Home Bike. I am wondering if anybody has successfully connect to the studio bike?
Thank you for the great work.

<img width="1639" height="1229" alt="Image" src="https://github.com/user-attachments/assets/d9aaa540-f051-4553-8e01-38cfc315c53b" />

<img width="1639" height="1229" alt="Image" src="https://github.com/user-attachments/assets/538066d7-025b-4158-b79f-2cadba7fe142" />

<img width="921" height="1229" alt="Image" src="https://github.com/user-attachments/assets/ddf1c0a8-5341-4426-9504-b6fb35178d37" />

**Comment by cagnulein** [comment]
@igeo install the free app nrfconnect and show me a screenshot about the bike from this app. Let me know

**Comment by igeo** [comment]
@cagnulein thank you for the response. At this time, I don't know if this bike broadcast BLE or not. I tried nrfconnect  and scan doesn't show anything like a bike.

**Comment by cagnulein** [comment]
Show me a scan and I will double check it
