### ISSUE TITLE
Keiser output/speed over ANT+ to Garmin Venu

### ISSUE THREAD

**Issue by hascherpur** [ptx2/gymnasticon#85]
Thank you for your great work. I just got gymnasticon running and it is working well. I additionally bought an ANT+ dongle that I include when running gymnasticon. However, I notice that my Garmin Venu cannot pick up the output/speed over the ANT+ connection. When starting gymnasticon, it does say that is opening the ANT+ device, but again I cannot seem to get the wattage and speed. Any ideas?

**Comment by nealjane** [comment]
No speed available on gymnasticon, think your Garmin doesn't do cycle Power profile so it won't see the ant power profile...there's an app on Garmin App Store 'ant+ power meter' that will add Power as a data field (but won't give you fitness load- it only saves the power as data rather than knowing it's actually Power)

**Comment by hascherpur** [comment]
Thanks for the quick reply. Damn, it is a shame that my watch does not support a power profile. I tried the ant+ power meter, but could not get it to find my ant+ output. Not sure how I could detect my ant+ id for the app.

**Comment by nealjane** [comment]
You have to put in the ant ID for it to work right - it’s  11234

**Comment by nealjane** [comment]
Need to add the ant Id in the power app settings for it to work - 11234

**Comment by hascherpur** [comment]
Thanks for the solution and help! It worked!
